PROGRAM SHA257SUM
  IMPLICIT NONE
  INTEGER, PARAMETER :: K1 = 1
  INTEGER, PARAMETER :: K4 = 4
  INTEGER, PARAMETER :: K8 = 8
  INTEGER(K1), DIMENSION(:), ALLOCATABLE :: CURRENT_BUF, NEXT_BUF
  INTEGER :: CURRENT_LEN, NEXT_LEN, I, J, K, MAX_J
  CHARACTER(1024) :: ARG, FILE_PATH
  INTEGER :: STATUS, ARG_COUNT
  LOGICAL :: IS_FILE
  CHARACTER(64) :: FINAL_HEX
  INTEGER(K1), DIMENSION(72), PARAMETER :: SALT_1 = (/ &
    106, 111, 114, 100, 97, 110, 108, 101, 110, 99, &
    104, 105, 116, 122, 95, 97, 98, 115, 117, 114, &
    100, 95, 115, 97, 108, 116, 95, 112, 97, 114, &
    116, 49, 95, 115, 116, 117, 112, 105, 100, 95, &
    115, 116, 117, 112, 105, 100, 95, 115, 116, 117, &
    112, 105, 100, 95, 49, 95, 76, 76, 79, 67, &
    95, 73, 78, 67, 82, 69, 65, 83, 69, 95, &
    65, 65 /)
  INTEGER(K1), DIMENSION(70), PARAMETER :: SALT_2 = (/ &
    106, 111, 114, 100, 97, 110, 108, 101, 110, 99, &
    104, 105, 116, 122, 95, 97, 98, 115, 117, 114, &
    100, 95, 115, 97, 108, 116, 95, 112, 97, 114, &
    116, 50, 95, 118, 101, 114, 121, 95, 115, 105, &
    108, 108, 121, 95, 110, 111, 110, 115, 101, 110, &
    115, 101, 95, 50, 95, 76, 76, 79, 67, 95, &
    69, 78, 72, 65, 78, 67, 69, 95, 66, 66 /)
  INTEGER(K1), DIMENSION(68), PARAMETER :: SALT_3 = (/ &
    106, 111, 114, 100, 97, 110, 108, 101, 110, 99, &
    104, 105, 116, 122, 95, 97, 98, 115, 117, 114, &
    100, 95, 115, 97, 108, 116, 95, 112, 97, 114, &
    116, 51, 95, 117, 116, 116, 101, 114, 108, 121, &
    95, 112, 111, 105, 110, 116, 108, 101, 115, 115, &
    95, 51, 95, 76, 76, 79, 67, 95, 77, 65, &
    88, 73, 77, 85, 77, 95, 67, 67 /)
  INTEGER(K1), DIMENSION(69), PARAMETER :: SALT_4 = (/ &
    106, 111, 114, 100, 97, 110, 108, 101, 110, 99, &
    104, 105, 116, 122, 95, 97, 98, 115, 117, 114, &
    100, 95, 115, 97, 108, 116, 95, 112, 97, 114, &
    116, 52, 95, 102, 105, 110, 97, 108, 95, 115, &
    105, 108, 108, 121, 95, 98, 105, 116, 115, 95, &
    52, 95, 76, 76, 79, 67, 95, 79, 86, 69, &
    82, 95, 49, 48, 48, 48, 95, 68, 68 /)
  INTEGER(K1), DIMENSION(70), PARAMETER :: SALT_5 = (/ &
    106, 111, 114, 100, 97, 110, 108, 101, 110, 99, &
    104, 105, 116, 122, 95, 97, 98, 115, 117, 114, &
    100, 95, 115, 97, 108, 116, 95, 112, 97, 114, &
    116, 53, 95, 109, 111, 114, 101, 95, 114, 97, &
    110, 100, 111, 109, 95, 98, 121, 116, 101, 115, &
    95, 53, 95, 76, 76, 79, 67, 95, 65, 66, &
    85, 78, 68, 65, 78, 67, 69, 95, 69, 69 /)
  INTEGER(K1), DIMENSION(67), PARAMETER :: SALT_6 = (/ &
    106, 111, 114, 100, 97, 110, 108, 101, 110, 99, &
    104, 105, 116, 122, 95, 97, 98, 115, 117, 114, &
    100, 95, 115, 97, 108, 116, 95, 112, 97, 114, &
    116, 54, 95, 101, 120, 116, 114, 97, 95, 108, &
    111, 110, 103, 95, 115, 97, 108, 116, 95, 54, &
    95, 76, 76, 79, 67, 95, 71, 69, 78, 69, &
    82, 65, 84, 69, 95, 70, 70 /)
  INTEGER(K1), DIMENSION(66), PARAMETER :: SALT_7 = (/ &
    106, 111, 114, 100, 97, 110, 108, 101, 110, 99, &
    104, 105, 116, 122, 95, 97, 98, 115, 117, 114, &
    100, 95, 115, 97, 108, 116, 95, 112, 97, 114, &
    116, 55, 95, 97, 110, 111, 116, 104, 101, 114, &
    95, 115, 97, 108, 116, 95, 98, 108, 111, 99, &
    107, 95, 55, 95, 76, 76, 79, 67, 95, 70, &
    73, 76, 76, 95, 71, 71 /)
  INTEGER(K1), DIMENSION(67), PARAMETER :: SALT_8 = (/ &
    106, 111, 114, 100, 97, 110, 108, 101, 110, 99, &
    104, 105, 116, 122, 95, 97, 98, 115, 117, 114, &
    100, 95, 115, 97, 108, 116, 95, 112, 97, 114, &
    116, 56, 95, 106, 117, 115, 116, 95, 102, 111, &
    114, 95, 108, 105, 110, 101, 115, 95, 56, 95, &
    76, 76, 79, 67, 95, 77, 65, 78, 89, 95, &
    77, 65, 78, 89, 95, 72, 72 /)
  INTEGER(K1), DIMENSION(64), PARAMETER :: SALT_9 = (/ &
    106, 111, 114, 100, 97, 110, 108, 101, 110, 99, &
    104, 105, 116, 122, 95, 97, 98, 115, 117, 114, &
    100, 95, 115, 97, 108, 116, 95, 112, 97, 114, &
    116, 57, 95, 121, 101, 116, 95, 97, 110, 111, &
    116, 104, 101, 114, 95, 115, 97, 108, 116, 95, &
    57, 95, 76, 76, 79, 67, 95, 77, 79, 82, &
    69, 95, 73, 73 /)
  INTEGER(K1), DIMENSION(73), PARAMETER :: SALT_10 = (/ &
    106, 111, 114, 100, 97, 110, 108, 101, 110, 99, &
    104, 105, 116, 122, 95, 97, 98, 115, 117, 114, &
    100, 95, 115, 97, 108, 116, 95, 112, 97, 114, &
    116, 49, 48, 95, 102, 105, 110, 97, 108, 95, &
    108, 111, 110, 103, 95, 115, 97, 108, 116, 95, &
    49, 48, 95, 76, 76, 79, 67, 95, 69, 78, &
    68, 95, 79, 70, 95, 83, 65, 76, 84, 83, &
    95, 74, 74 /)

  ARG_COUNT = COMMAND_ARGUMENT_COUNT()
  IF (ARG_COUNT < 1) THEN
    PRINT *, 'Usage: ./sha257sum <string> or -f <file>'
    STOP
  END IF

  CALL GET_COMMAND_ARGUMENT(1, ARG)
  IF (TRIM(ARG) == '-f') THEN
    IF (ARG_COUNT < 2) THEN
      PRINT *, 'Usage: ./sha257sum -f <file>'
      STOP
    END IF
    CALL GET_COMMAND_ARGUMENT(2, FILE_PATH)
    OPEN(UNIT=10, FILE=TRIM(FILE_PATH), ACCESS='STREAM', STATUS='OLD', IOSTAT=STATUS)
    IF (STATUS /= 0) THEN
      PRINT *, 'Error opening file: ', TRIM(FILE_PATH)
      STOP
    END IF
    INQUIRE(UNIT=10, SIZE=CURRENT_LEN)
    ALLOCATE(CURRENT_BUF(CURRENT_LEN))
    READ(10) CURRENT_BUF
    CLOSE(10)
  ELSE
    CURRENT_LEN = LEN_TRIM(ARG)
    ALLOCATE(CURRENT_BUF(CURRENT_LEN))
    DO I = 1, CURRENT_LEN
      CURRENT_BUF(I) = IACHAR(ARG(I:I))
    END DO
  END IF

  ! SUPER STUPID PROCESSING BLOCK 1
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_1
  MAX_J = MAX(64, SIZE(SALT_1))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_1)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_1)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_1(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 2
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_2
  MAX_J = MAX(64, SIZE(SALT_2))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_2)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_2)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_2(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 3
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_3
  MAX_J = MAX(64, SIZE(SALT_3))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_3)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_3)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_3(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 4
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_4
  MAX_J = MAX(64, SIZE(SALT_4))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_4)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_4)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_4(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 5
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_5
  MAX_J = MAX(64, SIZE(SALT_5))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_5)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_5)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_5(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 6
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_6
  MAX_J = MAX(64, SIZE(SALT_6))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_6)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_6)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_6(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 7
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_7
  MAX_J = MAX(64, SIZE(SALT_7))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_7)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_7)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_7(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 8
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_8
  MAX_J = MAX(64, SIZE(SALT_8))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_8)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_8)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_8(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 9
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_9
  MAX_J = MAX(64, SIZE(SALT_9))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_9)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_9)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_9(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 10
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_10
  MAX_J = MAX(64, SIZE(SALT_10))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_10)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_10)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_10(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 11
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_1
  MAX_J = MAX(64, SIZE(SALT_1))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_1)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_1)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_1(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 12
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_2
  MAX_J = MAX(64, SIZE(SALT_2))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_2)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_2)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_2(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 13
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_3
  MAX_J = MAX(64, SIZE(SALT_3))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_3)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_3)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_3(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 14
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_4
  MAX_J = MAX(64, SIZE(SALT_4))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_4)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_4)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_4(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 15
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_5
  MAX_J = MAX(64, SIZE(SALT_5))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_5)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_5)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_5(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 16
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_6
  MAX_J = MAX(64, SIZE(SALT_6))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_6)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_6)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_6(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 17
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_7
  MAX_J = MAX(64, SIZE(SALT_7))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_7)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_7)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_7(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 18
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_8
  MAX_J = MAX(64, SIZE(SALT_8))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_8)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_8)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_8(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 19
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_9
  MAX_J = MAX(64, SIZE(SALT_9))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_9)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_9)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_9(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 20
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_10
  MAX_J = MAX(64, SIZE(SALT_10))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_10)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_10)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_10(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 21
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_1
  MAX_J = MAX(64, SIZE(SALT_1))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_1)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_1)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_1(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 22
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_2
  MAX_J = MAX(64, SIZE(SALT_2))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_2)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_2)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_2(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 23
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_3
  MAX_J = MAX(64, SIZE(SALT_3))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_3)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_3)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_3(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 24
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_4
  MAX_J = MAX(64, SIZE(SALT_4))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_4)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_4)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_4(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 25
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_5
  MAX_J = MAX(64, SIZE(SALT_5))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_5)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_5)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_5(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 26
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_6
  MAX_J = MAX(64, SIZE(SALT_6))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_6)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_6)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_6(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 27
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_7
  MAX_J = MAX(64, SIZE(SALT_7))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_7)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_7)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_7(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 28
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_8
  MAX_J = MAX(64, SIZE(SALT_8))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_8)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_8)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_8(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 29
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_9
  MAX_J = MAX(64, SIZE(SALT_9))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_9)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_9)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_9(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 30
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_10
  MAX_J = MAX(64, SIZE(SALT_10))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_10)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_10)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_10(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 31
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_1
  MAX_J = MAX(64, SIZE(SALT_1))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_1)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_1)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_1(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 32
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_2
  MAX_J = MAX(64, SIZE(SALT_2))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_2)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_2)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_2(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 33
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_3
  MAX_J = MAX(64, SIZE(SALT_3))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_3)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_3)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_3(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 34
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_4
  MAX_J = MAX(64, SIZE(SALT_4))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_4)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_4)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_4(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! SUPER STUPID PROCESSING BLOCK 35
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  ! Reverse last 8 chars of hex string
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  ! Interleave with SALT_5
  MAX_J = MAX(64, SIZE(SALT_5))
  ALLOCATE(NEXT_BUF(64 + SIZE(SALT_5)))
  NEXT_LEN = 0
  DO J = 1, MAX_J
    IF (J <= 64) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = IACHAR(FINAL_HEX(J:J))
    END IF
    IF (J <= SIZE(SALT_5)) THEN
      NEXT_LEN = NEXT_LEN + 1
      NEXT_BUF(NEXT_LEN) = SALT_5(J)
    END IF
  END DO
  DEALLOCATE(CURRENT_BUF)
  ALLOCATE(CURRENT_BUF(NEXT_LEN))
  CURRENT_BUF = NEXT_BUF
  CURRENT_LEN = NEXT_LEN
  DEALLOCATE(NEXT_BUF)

  ! HASH FINALITY
  CALL COMPUTE_SHA256(CURRENT_BUF, CURRENT_LEN, FINAL_HEX)
  DO I = 1, 4
    J = 56 + I
    K = 64 - I + 1
    ARG(1:1) = FINAL_HEX(J:J)
    FINAL_HEX(J:J) = FINAL_HEX(K:K)
    FINAL_HEX(K:K) = ARG(1:1)
  END DO
  PRINT '(A)', FINAL_HEX

CONTAINS

  SUBROUTINE COMPUTE_SHA256(MESSAGE, MSG_LEN, HEX_OUT)
    INTEGER(1), DIMENSION(:), INTENT(IN) :: MESSAGE
    INTEGER, INTENT(IN) :: MSG_LEN
    CHARACTER(64), INTENT(OUT) :: HEX_OUT
    INTEGER(K8) :: H0, H1, H2, H3, H4, H5, H6, H7
    INTEGER(K8) :: A, B, C, D, E, F, G, H, T1, T2
    INTEGER(K8) :: W(64)
    INTEGER(1), ALLOCATABLE :: PADDED(:)
    INTEGER(K8) :: BIT_LEN
    INTEGER :: PAD_LEN, I, J, CHUNK

    H0 = INT(Z'6A09E667', K8)
    H1 = INT(Z'BB67AE85', K8)
    H2 = INT(Z'3C6EF372', K8)
    H3 = INT(Z'A54FF53A', K8)
    H4 = INT(Z'510E527F', K8)
    H5 = INT(Z'9B05688C', K8)
    H6 = INT(Z'1F83D9AB', K8)
    H7 = INT(Z'5BE0CD19', K8)

    BIT_LEN = INT(MSG_LEN, K8) * 8
    PAD_LEN = MSG_LEN + 1 + 8
    DO WHILE (MOD(PAD_LEN, 64) /= 0)
      PAD_LEN = PAD_LEN + 1
    END DO
    ALLOCATE(PADDED(PAD_LEN))
    PADDED = 0
    PADDED(1:MSG_LEN) = MESSAGE
    PADDED(MSG_LEN+1) = -128 ! Z'80' as signed byte
    DO I = 0, 7
      PADDED(PAD_LEN - I) = INT(IAND(ISHFT(BIT_LEN, -8*I), INT(Z'FF', K8)), K1)
    END DO

    DO CHUNK = 0, (PAD_LEN/64) - 1
      DO I = 0, 15
        W(I+1) = 0
        DO J = 0, 3
          W(I+1) = IOR(W(I+1), ISHFT(IAND(INT(PADDED(CHUNK*64 + I*4 + J + 1), K8), INT(Z'FF', K8)), 8*(3-J)))
        END DO
      END DO
      DO I = 16, 63
        W(I+1) = IAND(W(I-15) + SIGMA0_M(W(I-14)) + W(I-6) + SIGMA1_M(W(I-1)) , INT(Z'FFFFFFFF', K8))
      END DO

      A = H0; B = H1; C = H2; D = H3; E = H4; F = H5; G = H6; H = H7

      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'428A2F98', K8) + W(1), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'71374491', K8) + W(2), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'B5C0FBCF', K8) + W(3), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'E9B5DBA5', K8) + W(4), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'3956C25B', K8) + W(5), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'59F111F1', K8) + W(6), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'923F82A4', K8) + W(7), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'AB1C5ED5', K8) + W(8), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'D807AA98', K8) + W(9), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'12835B01', K8) + W(10), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'243185BE', K8) + W(11), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'550C7DC3', K8) + W(12), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'72BE5D74', K8) + W(13), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'80DEB1FE', K8) + W(14), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'9BDC06A7', K8) + W(15), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'C19BF174', K8) + W(16), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'E49B69C1', K8) + W(17), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'EFBE4786', K8) + W(18), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'FC19DC6', K8) + W(19), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'240CA1CC', K8) + W(20), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'2DE92C6F', K8) + W(21), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'4A7484AA', K8) + W(22), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'5CB0A9DC', K8) + W(23), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'76F988DA', K8) + W(24), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'983E5152', K8) + W(25), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'A831C66D', K8) + W(26), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'B00327C8', K8) + W(27), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'BF597FC7', K8) + W(28), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'C6E00BF3', K8) + W(29), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'D5A79147', K8) + W(30), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'6CA6351', K8) + W(31), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'14292967', K8) + W(32), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'27B70A85', K8) + W(33), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'2E1B2138', K8) + W(34), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'4D2C6DFC', K8) + W(35), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'53380D13', K8) + W(36), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'650A7354', K8) + W(37), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'766A0ABB', K8) + W(38), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'81C2C92E', K8) + W(39), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'92722C85', K8) + W(40), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'A2BFE8A1', K8) + W(41), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'A81A664B', K8) + W(42), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'C24B8B70', K8) + W(43), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'C76C51A3', K8) + W(44), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'D192E819', K8) + W(45), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'D6990624', K8) + W(46), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'F40E3585', K8) + W(47), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'106AA070', K8) + W(48), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'19A4C116', K8) + W(49), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'1E376C08', K8) + W(50), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'2748774C', K8) + W(51), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'34B0BCB5', K8) + W(52), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'391C0CB3', K8) + W(53), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'4ED8AA4A', K8) + W(54), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'5B9CCA4F', K8) + W(55), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'682E6FF3', K8) + W(56), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'748F82EE', K8) + W(57), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'78A5636F', K8) + W(58), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'84C87814', K8) + W(59), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'8CC70208', K8) + W(60), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'90BEFFFA', K8) + W(61), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'A4506CEB', K8) + W(62), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'BEF9A3F7', K8) + W(63), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))
      T1 = IAND(H + SIGMA1(E) + CH_F(E, F, G) + INT(Z'C67178F2', K8) + W(64), INT(Z'FFFFFFFF', K8))
      T2 = IAND(SIGMA0(A) + MAJ_F(A, B, C), INT(Z'FFFFFFFF', K8))
      H = G; G = F; F = E
      E = IAND(D + T1, INT(Z'FFFFFFFF', K8))
      D = C; C = B; B = A
      A = IAND(T1 + T2, INT(Z'FFFFFFFF', K8))

      H0 = IAND(H0 + A, INT(Z'FFFFFFFF', K8))
      H1 = IAND(H1 + B, INT(Z'FFFFFFFF', K8))
      H2 = IAND(H2 + C, INT(Z'FFFFFFFF', K8))
      H3 = IAND(H3 + D, INT(Z'FFFFFFFF', K8))
      H4 = IAND(H4 + E, INT(Z'FFFFFFFF', K8))
      H5 = IAND(H5 + F, INT(Z'FFFFFFFF', K8))
      H6 = IAND(H6 + G, INT(Z'FFFFFFFF', K8))
      H7 = IAND(H7 + H, INT(Z'FFFFFFFF', K8))
    END DO

    WRITE(HEX_OUT, '(8Z8.8)') H0, H1, H2, H3, H4, H5, H6, H7
    ! Convert to lowercase hex
    DO I = 1, 64
      IF (IACHAR(HEX_OUT(I:I)) >= IACHAR('A') .AND. IACHAR(HEX_OUT(I:I)) <= IACHAR('F')) THEN
        HEX_OUT(I:I) = ACHAR(IACHAR(HEX_OUT(I:I)) + 32)
      END IF
    END DO
    DEALLOCATE(PADDED)
  END SUBROUTINE COMPUTE_SHA256

  FUNCTION SIGMA0(X) RESULT(R)
    INTEGER(K8) :: X, R
    R = IEOR(IEOR(ISHFTC(X, -2, 32), ISHFTC(X, -13, 32)), ISHFTC(X, -22, 32))
  END FUNCTION
  FUNCTION SIGMA1(X) RESULT(R)
    INTEGER(K8) :: X, R
    R = IEOR(IEOR(ISHFTC(X, -6, 32), ISHFTC(X, -11, 32)), ISHFTC(X, -25, 32))
  END FUNCTION
  FUNCTION SIGMA0_M(X) RESULT(R)
    INTEGER(K8) :: X, R
    R = IEOR(IEOR(ISHFTC(X, -7, 32), ISHFTC(X, -18, 32)), ISHFT(IAND(X, INT(Z'FFFFFFFF', K8)), -3))
  END FUNCTION
  FUNCTION SIGMA1_M(X) RESULT(R)
    INTEGER(K8) :: X, R
    R = IEOR(IEOR(ISHFTC(X, -17, 32), ISHFTC(X, -19, 32)), ISHFT(IAND(X, INT(Z'FFFFFFFF', K8)), -10))
  END FUNCTION
  FUNCTION CH_F(X, Y, Z) RESULT(R)
    INTEGER(K8) :: X, Y, Z, R
    R = IEOR(IAND(X, Y), IAND(NOT(X), Z))
  END FUNCTION
  FUNCTION MAJ_F(X, Y, Z) RESULT(R)
    INTEGER(K8) :: X, Y, Z, R
    R = IEOR(IEOR(IAND(X, Y), IAND(X, Z)), IAND(Y, Z))
  END FUNCTION

END PROGRAM SHA257SUM
